// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace rpiDaemon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    internal class SensorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("rpiDaemon.Models.SensorReadingModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<DateTime>("MeasuredAtUtc")
                    .HasColumnType("datetime2");

                b.Property<double>("TemperatureInDegreesC")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.ToTable("SensorReadings");
            });
#pragma warning restore 612, 618
        }
    }
}