services:
  rpidaemon:
    image: aopheim/rpidaemon:latest
    ports:
      - 80
    restart: unless-stopped
  birdnetserver:
    image: mmcc73/birdnetserver2.4_arm64:latest
    ports:
      - 8080
    restart: unless-stopped
