services:
  rpidaemon:
    extends:
      file: docker-compose.yml
      service: rpidaemon
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LD_LIBRARY_PATH=/opt/vc/lib
      - LD_DEBUG=all
    volumes:
      - /home/pi/.microsoft/usersecrets/7a7d43a7-4a55-45c9-b915-7c7aec6d1751:/root/.microsoft/usersecrets/7a7d43a7-4a55-45c9-b915-7c7aec6d1751
      - /home/pi/audioRecordings:/audioRecordings
      - /home/pi/images:/images
      - /opt/vc/lib:/opt/vc/lib
      - /opt/vc/bin:/opt/vc/bin
    depends_on:
      # - birdnetserver
      - audiorecorderlinux
    devices:
      # Camera
      - "/dev/vchiq:/dev/vchiq"
      # GPIO
      - "/sys/class/gpio:/sys/class/gpio"
    privileged: true
  birdnetserver:
    extends:
      file: docker-compose.yml
      service: birdnetserver
  audiorecorderlinux:
    image: aopheim/audiorecorderlinux:latest
    ports:
      - 4000
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
    volumes:
      - /home/pi/audioRecordings:/audioRecordings
