services:
  rpidaemon:
    image: aopheim/rpidaemon:latest
    ports:
      - 80
    restart: unless-stopped
  # birdnetserver:
  #   image: aopheim/birdnetserver:latest
  #   ports:
  #     - 8080
  #   restart: unless-stopped
