// <auto-generated />
using System;
using DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace rpiDaemon.Migrations
{
    [DbContext(typeof(BudorDbContext))]
    [Migration("20260521200000_AddVideoUploadRepo")]
    partial class AddVideoUploadRepo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shared.Models.BirdPresenceRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BirdPresenceRegistrations");
                });

            modelBuilder.Entity("Shared.Models.HiddenSpeciesModel", b =>
                {
                    b.Property<string>("TaxonomySpeciesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TaxonomySpeciesId");

                    b.ToTable("HiddenSpecies");
                });

            modelBuilder.Entity("Shared.Models.ImageUploadModel", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullSizeImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailJpgImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailWebPImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileName");

                    b.ToTable("ImageUploads");
                });

            modelBuilder.Entity("Shared.Models.SensorReadingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AltitudeInMeters")
                        .HasColumnType("float");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("PressureInhPa")
                        .HasColumnType("float");

                    b.Property<double>("RelativeHumidityInPercent")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureInDegreesC")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("Shared.Models.SpeciesRecognitionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecognizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SpeciesRecognitions");
                });

            modelBuilder.Entity("Shared.Models.VideoUploadModel", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileName");

                    b.ToTable("VideoUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
